FROM ubuntu

# Install pamtester todo remove
RUN set -xe; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		"pamtester" \
		"nano" \
	; \
	rm -fr /tmp/* ; \
	rm -rf /var/lib/apt/lists/*;

# Install pam_oidc_auth
ADD pam_oidc_auth.so /lib/x86_64-linux-gnu/security/pam_oidc_auth.so

# Add PAM config
RUN echo "auth required pam_oidc_auth.so discovery_url=http://oidc-server-mock:8080/.well-known/openid-configuration audience=some-app username_claim=sub" > /etc/pam.d/oidc_auth

RUN echo '#!/bin/bash \n pamtester oidc_auth $1 authenticate <<< "$TEST_TOKEN"; exit $?' > testpam.sh
RUN chmod +x testpam.sh

#CMD [ "sleep", "infinity"]
CMD [ "./testpam.sh", "someuser@company.com"]
