FROM ubuntu

# Install pamtester todo remove
RUN set -xe; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		"pamtester" \
		"nano" \
	; \
	rm -fr /tmp/* ; \
	rm -rf /var/lib/apt/lists/*;

# Install pam_oidc_auth
ADD pam_oidc_auth /usr/local/bin/pam_oidc_auth

# Add Permissions
RUN chmod 555 /usr/local/bin/pam_oidc_auth

# Add PAM config
RUN echo "auth required pam_exec.so expose_authtok /usr/local/bin/pam_oidc_auth" > /etc/pam.d/oidc_auth
RUN echo "account required pam_permit.so" >> /etc/pam.d/oidc_auth

RUN echo '#!/bin/bash \n pamtester oidc_auth $1 authenticate <<< "$TEST_TOKEN"; exit $?' > testpam.sh
RUN chmod +x testpam.sh

#CMD [ "sleep", "infinity"]
CMD [ "./testpam.sh", "someuser@company.com"]
