
#FROM postgres:16-bookworm
#FROM postgres:16-bullseye
#FROM postgis/postgis:16-3.5
FROM ghcr.io/cloudnative-pg/postgresql:16-bookworm

USER root

# Install addons
RUN apt-get update \
    && apt-get install -y lsb-release wget \
    && echo "deb https://packagecloud.io/timescale/timescaledb/debian/ $(lsb_release -c -s) main" | tee /etc/apt/sources.list.d/timescaledb.list \
    && wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | apt-key add - \
    && apt-get update \
    && apt-get install -y \
        "timescaledb-2-postgresql-${PG_MAJOR}=${TIMESCALE_VERSION}*" \
	    "timescaledb-toolkit-postgresql-${PG_MAJOR}" \
        "postgresql-${PG_MAJOR}-cron" \
    && apt-get remove -y lsb-release wget \
    && 	rm -fr /tmp/* \
    && 	rm -rf /var/lib/apt/lists/*

# Install pamtester
RUN set -xe; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        "pamtester" \
        "nano" \
    ; \
    rm -fr /tmp/* ; \
    rm -rf /var/lib/apt/lists/*;

# Install pam_oidc_auth
ADD pam_oidc_auth /usr/local/bin/pam_oidc_auth

# Add Permissions
RUN chmod 555 /usr/local/bin/pam_oidc_auth

# Add PAM config
RUN echo "auth required pam_exec.so expose_authtok log=/var/tmp/auth.log /usr/local/bin/pam_oidc_auth" > /etc/pam.d/oidc_auth
RUN echo "account required pam_permit.so" >> /etc/pam.d/oidc_auth

RUN echo '#!/bin/bash \n pamtester oidc_auth $1 authenticate <<< "$TEST_TOKEN"; exit $?' > testpam.sh
RUN chmod +x testpam.sh

# Without libssl a error would be displayed 'No usable version of libssl was found'
ADD https://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb .
RUN dpkg -i libssl1.0.0_1.0.2n-1ubuntu5.13_amd64.deb

USER 26

#CMD [ "./testpam.sh", "someuser@company.com"]